GET http://localhost:3000/notas

###

POST http://localhost:3000/notas
Content-Type: application/json

{
    "title": "Titulo de mi nota",
    "content": "Texto de mi nota"
}
###

DELETE http://localhost:3000/notas/123

###
PUT  http://localhost:3000/notas/69fb95674078c6fcab46c44b
Content-Type: application/json

{
    "title": "Titulo de mi nota actualizado",
    "content": "Texto de mi nota actualizado"
}